### ISSUE TITLE
SyntaxError Durring Startup

### ISSUE THREAD

**Issue by bennythomps** [outworkers/phantom#477]
I am trying to make a basic connection to a local Cassandra instance but I am getting the following exception:

```
com.datastax.driver.core.exceptions.SyntaxError: line 1:70 mismatched character ';' expecting '$'
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:132) ~[cassandra-driver-core-3.0.0.jar:na]
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179) ~[cassandra-driver-core-3.0.0.jar:na]
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:184) ~[cassandra-driver-core-3.0.0.jar:na]
	at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:43) ~[cassandra-driver-core-3.0.0.jar:na]
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:798) ~[cassandra-driver-core-3.0.0.jar:na]
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:617) ~[cassandra-driver-core-3.0.0.jar:na]
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1005) ~[cassandra-driver-core-3.0.0.jar:na]
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:928) ~[cassandra-driver-core-3.0.0.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
```

Here is the line of my code that breaks:

```
ContactPoints(configuration.getStringSeq("cassandra.hosts").get).keySpace("testing")
```

**Comment by bennythomps** [comment]
My bad, I turned on debug logging and it a showed that the table name being generated was $anon something so C* was not happy.
