### ISSUE TITLE
how to run embedded cassandra in Intellij

### ISSUE THREAD

**Issue by jerrypaytm** [outworkers/phantom#552]
I'm using the phantom-sbt so that I can test actors against an embedded cassandra. It works fine with `sbt test` but if I want to debug in intellij, the phantom-sbt does not get execute properly. Is there any specific configuration that I need to be aware of to allow phantom-sbt to run inside intellij? Thanks!

**Comment by alexflav23** [comment]
Hi @jerrypaytm,

Thank you for reporting this. Is there a particular stack trace or error you are encountering? It would be really helpful if you could share a bit more information about what's going wrong.

Many thanks!

**Comment by jerrypaytm** [comment]
Hi @alexflav23,

This is the stack trace when I run the test within intellij:

```
Testing started at 12:41 PM ...

An exception or error caused a run to abort: All host(s) tried for query failed (tried: localhost/0:0:0:0:0:0:0:1:9142 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect), localhost/127.0.0.1:9142 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1] Cannot connect)) 
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/0:0:0:0:0:0:0:1:9142 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect), localhost/127.0.0.1:9142 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1424)
	at com.datastax.driver.core.Cluster.init(Cluster.java:163)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:334)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:309)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:251)
	at com.websudos.phantom.connectors.DefaultSessionProvider$$anonfun$1$$anonfun$2.apply(DefaultSessionProvider.scala:58)
	at com.websudos.phantom.connectors.DefaultSessionProvider$$anonfun$1$$anonfun$2.apply(DefaultSessionProvider.scala:58)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:123)
	at com.websudos.phantom.connectors.DefaultSessionProvider$$anonfun$1.apply(DefaultSessionProvider.scala:57)
	at com.websudos.phantom.connectors.DefaultSessionProvider$$anonfun$1.apply(DefaultSessionProvider.scala:56)
	at scala.util.Try$.apply(Try.scala:192)
	at com.websudos.phantom.connectors.DefaultSessionProvider.createSession(DefaultSessionProvider.scala:56)
	at com.websudos.phantom.connectors.DefaultSessionProvider.<init>(DefaultSessionProvider.scala:68)
	at com.websudos.phantom.connectors.KeySpaceDef.<init>(Keyspace.scala:85)
	at com.websudos.phantom.connectors.KeySpaceBuilder.keySpace(KeySpaceBuilder.scala:53)
```

**Comment by jerrypaytm** [comment]
I found a solution: 
```
![image](https://cloud.githubusercontent.com/assets/17746476/18810044/2a7df5ac-825a-11e6-9b0a-e3f3bd4db718.png)

```

**Comment by jerrypaytm** [comment]
However, the embedded database stays up even after the test finishes inside intellij. Is there a way to shut it down after the test?
