### ISSUE TITLE
Initialize table error

### ISSUE THREAD

**Issue by fggarcia** [outworkers/phantom#599]
When upgrade to 1.29.6 from 1.29.5, this error appear.

Revert to 1.29.5 solve the problem.

Caused by: java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.runtime.ReflectionUtils$.innerSingletonInstance(ReflectionUtils.scala:81)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaModuleMirror.instance(JavaMirrors.scala:531)
	at com.websudos.phantom.CassandraTable$$anonfun$7.apply(CassandraTable.scala:224)
	at com.websudos.phantom.CassandraTable$$anonfun$7.apply(CassandraTable.scala:222)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.websudos.phantom.CassandraTable.<init>(CassandraTable.scala:222)
	at com.despegar.departed.store.OtaPriceByDateCassandra.<init>(OtaStore.scala:95)
	at com.despegar.departed.store.OtaPriceCassandra$.<init>(OtaStore.scala:243)
	at com.despegar.departed.store.OtaPriceCassandra$.<clinit>(OtaStore.scala)

Any idea?
Do you need any information about table design?

**Comment by alexflav23** [comment]
Hi @fggarcia,

Yes please, apologies for the late reply, it would be good to understand what is going wrong.

Regards.

**Comment by alexflav23** [comment]
Hi @fggarcia,

Phantom 1.x series is now in maintenance mode, but with Phantom 2.0.0 now out you are much better off upgrading. I will close this ticket, if further work is required here please show some code and we will have a look.

Regards.
