### ISSUE TITLE
NotImplementedError - when missing "fromRow" method

### ISSUE THREAD

**Issue by 123avi** [outworkers/phantom#620]
Hi, using Phantom 2.0.0

My model includes _JsonColumn_ and _ListColumn_ (and other primitive columns ) . I am removed the "_fromRow_" method and getting _NotImplementedError_ on simple Select query (no problem with _Insert_ query) :
```

 def find(id: UUID) = select
    .where(_.id eqs id)
    .fetch()

```
yields this:
```

Caused by: scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:230)
	at com.xpiryens.model.InstallationModel$$anon$1.fromRow(MyModel.scala:22)
	at com.xpiryens.model.InstallationModel$$anon$1.fromRow(IMyModel.scala:22)
	at com.outworkers.phantom.CassandraTable.fromRow(CassandraTable.scala:81)
	at com.outworkers.phantom.SelectTable$$anonfun$select$1.apply(SelectTable.scala:9)
	at com.outworkers.phantom.SelectTable$$anonfun$select$1.apply(SelectTable.scala:9)
	at com.outworkers.phantom.builder.query.SelectQuery.fromRow(SelectQuery.scala:58)
	at com.outworkers.phantom.builder.query.RootExecutableQuery$class.directMapper(ExecutableQuery.scala:161)
	at com.outworkers.phantom.builder.query.SelectQuery.directMapper(SelectQuery.scala:32)
	at com.outworkers.phantom.builder.query.ExecutableQuery$$anonfun$fetch$1.apply(ExecutableQuery.scala:235)
	at com.outworkers.phantom.builder.query.ExecutableQuery$$anonfun$fetch$1.apply(ExecutableQuery.scala:235)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	... 6 more

```
of course implementing the fromRow method solved that.

**Comment by alexflav23** [comment]
Hi @123avi Phantom will tell you if it was able to automatically derive your extractor or not, read the compilation bugs, if it wasn't you will still need to define the `fromRow` yourself. This is not a bug, this is an impedance mismatch between your table and case class fields.

Should you require more help, please post more code, e.g the case class and table.

**Comment by 123avi** [comment]
Thanks, IHMO the error message is misleading. but I understand what do you mean . thanks
