### ISSUE TITLE
Possible compatibility with play framework 2.5.x?

### ISSUE THREAD

**Issue by meddulla** [outworkers/phantom#658]
Hi,

I'm currently upgrading from Play Framework 2.4.6 to 2.5.10. Using Phantom 1.21.0 (and the same previously working code) I get this error:

```
Caused by: java.lang.reflect.InvocationTargetException
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:497)
[error] 	at scala.reflect.runtime.ReflectionUtils$.innerSingletonInstance(ReflectionUtils.scala:81)
[error] 	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaModuleMirror.instance(JavaMirrors.scala:531)
[error] 	at com.websudos.phantom.CassandraTable$$anonfun$6.apply(CassandraTable.scala:208)
[error] 	at com.websudos.phantom.CassandraTable$$anonfun$6.apply(CassandraTable.scala:207)
[error] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error] 	at com.websudos.phantom.CassandraTable.<init>(CassandraTable.scala:206)
[error] 	at com.puregroup.core.database.ShareClassMeta.<init>(ShareClassMeta.scala:48)
[error] 	at com.puregroup.core.database.ShareClassMetaCol.<init>(ShareClassMeta.scala:180)
[error] 	at com.puregroup.core.database.Collections$ShareClassMeta$.<init>(DbClient.scala:61)
[error] 	at com.puregroup.core.database.Collections.ShareClassMeta$lzycompute(DbClient.scala:61)
[error] 	at com.puregroup.core.database.Collections.ShareClassMeta(DbClient.scala:61)
[error] 	... 38 more
[error] Caused by: java.lang.NoSuchMethodError: play.api.libs.functional.syntax.package$.functionalCanBuildApplicative(Lplay/api/libs/functional/Applicative;)Lplay/api/libs/functional/FunctionalCanBuild
```

I'm guessing this might be a compatibility issue but not sure..  Any idea?

Thanks

**Comment by alexflav23** [comment]
Hi @meddulla,

Which version of phantom are you using?

Regards.

**Comment by meddulla** [comment]
Hi @alexflav23,

1.21.0

```

val PhantomVersion = "1.21.0"

libraryDependencies ++= Seq(
  "com.websudos" %% "phantom-dsl" % PhantomVersion,
  "com.websudos" %% "phantom-testkit" % "1.12.2" % "test, provided"
)
```

Thank you for any help

**Comment by alexflav23** [comment]
This is very old, have a look at the [migration docs].
 It won't be as much as 123, but it comes with a plethora of improvements.
 (https://github.com/outworkers/phantom/blob/develop/docs/migrate.md).

```
val PhantomVersion = "2.6.4"

libraryDependencies ++= Seq(
  "com.outworkers" %% "phantom-dsl" % PhantomVersion
)
```

**Comment by meddulla** [comment]
Ok, thanks. I'll start on it. 

On a related question, is there currently any activator template that uses the latest play version? Looked at https://github.com/outworkers/phantom-activator-template but seems outdated - maybe there's another?

Thanks

**Comment by meddulla** [comment]
After I upgrade the project I'm on and understand all the changes required, I'd be happy to do a pull request on that activator template if you'd be interested.

Cheers

**Comment by alexflav23** [comment]
Hi @meddulla,

Pull requests are more than welcome!

Regards.
