### ISSUE TITLE
StackOverflowError when creating a new table in v2.7.0 with a secondary index

### ISSUE THREAD

**Issue by leoromanovsky** [outworkers/phantom#664]
For a table with schema like this:

```
class LeaderboardsTable extends CassandraTable[LeaderboardsTable, LeaderboardEntry] {

  override val tableName = "leaderboards"

  object section_id extends IntColumn(this) with PartitionKey
  object elapsed_time extends IntColumn(this) with PrimaryKey with ClusteringOrder with Ascending
  object user_id extends IntColumn(this) with Index

  override def fromRow(r: Row) ...
}
```

The following exception is seen when creating a table:

```
[info]   java.lang.StackOverflowError:
[info]   at LeaderboardsTable$anon$macro$1$1.fields(LeaderboardsTable.scala:20)
[info]   at LeaderboardsTable$anon$macro$1$1.fields(LeaderboardsTable.scala:20)
[info]   at com.outworkers.phantom.CassandraTable.columns(CassandraTable.scala:39)
[info]   at com.outworkers.phantom.CassandraTable.secondaryKeys(CassandraTable.scala:41)
[info]   at com.outworkers.phantom.finagle.package$CreateQueryAugmenter$.execute$extension(package.scala:293)
[info]   at com.outworkers.phantom.finagle.package$CreateQueryAugmenter$.execute$extension(package.scala:296)
[info]   at com.outworkers.phantom.finagle.package$CreateQueryAugmenter$.execute$extension(package.scala:296)
[info]   at com.outworkers.phantom.finagle.package$CreateQueryAugmenter$.execute$extension(package.scala:296)
[info]   at com.outworkers.phantom.finagle.package$CreateQueryAugmenter$.execute$extension(package.scala:296)
[info]   at com.outworkers.phantom.finagle.package$CreateQueryAugmenter$.execute$extension(package.scala:296)
[info]   ...
```

Please let me know if I could provide further context.

**Comment by alexflav23** [comment]
Apologies for this oversight, it was really stupid of me now that I look at it, this one is entirely my fault, `CreateQuery` has a `super.future`, but the augmented package object has no such thing, so the `execute` function was calling itself recursively. 

If you have more bugs with `finagle` support or suggestions please keep them coming, there are not a lot of users so if things break they are harder to keep track of.

Fixed in #666. Yes you got the magic number today 💯 , will go on Maven Central as 2.7.2 in about 2 hours.
