### ISSUE TITLE
How to import Phantom in IntelliJ

### ISSUE THREAD

**Issue by EddyP23** [outworkers/phantom#726]
I cloned the whole project and I am trying to import it in IntelliJ, but I get the following error:
```

Error while importing SBT project: ... 
at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:374)
at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:148)
at com.typesafe.sbt.git.JGit.hasUncommittedChanges(JGit.scala:84)
at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8$$anonfun$apply$8.apply(SbtGit.scala:116)
at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8$$anonfun$apply$8.apply(SbtGit.scala:116)
at com.typesafe.sbt.git.DefaultReadableGit.withGit(ReadableGit.scala:35)
at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8.apply(SbtGit.scala:116)
at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8.apply(SbtGit.scala:116)
at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
[error] org.eclipse.jgit.api.errors.JGitInternalException: Invalid path: phantom-dsl/src/main/scala/com/outworkers/phantom/macros/==:==.scala
[error] Use 'last' for the full log.
Invalid response.
```

Any ideas how I should fix this?

Some details:
IntelliJ v2017.1.5
JDK 1.8.0_131

**Comment by alexflav23** [comment]
Hi @EddyP23 Please phrase your question better, I don't really know what you want based on the title of this.

**Comment by EddyP23** [comment]
Yes, sorry, I misclicked and posted the question without the body :(

**Comment by EddyP23** [comment]
It seems like it is not IntelliJ problem. I guess, it's more of a windows compatibility issue. When I try to run `sbt compile` I get a very similar exception:

```
org.eclipse.jgit.api.errors.JGitInternalException: Invalid path: phantom-dsl/src/main/scala/com/outworkers/phantom/macros/==:==.scala
        at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:154)
        at com.typesafe.sbt.git.JGit.hasUncommittedChanges(JGit.scala:84)
        at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8$$anonfun$apply$8.apply(SbtGit.scala:116)
        at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8$$anonfun$apply$8.apply(SbtGit.scala:116)
        at com.typesafe.sbt.git.DefaultReadableGit.withGit(ReadableGit.scala:35)
        at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8.apply(SbtGit.scala:116)
        at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8.apply(SbtGit.scala:116)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.eclipse.jgit.errors.CorruptObjectException: Invalid path: phantom-dsl/src/main/scala/com/outworkers/phantom/macros/==:==.scala
        at org.eclipse.jgit.dircache.DirCacheEntry.<init>(DirCacheEntry.java:196)
        at org.eclipse.jgit.dircache.DirCache.readFrom(DirCache.java:483)
```

I am on Windows 10.

**Comment by EddyP23** [comment]
OK, it turns out it is a windows issue. Colon is not allowed in file names in windows, but it is allowed in Linux/Unix systems (simplest source: https://stackoverflow.com/a/31976060/5018962).

It would be much appreciated, if this could be solved at some point.

**Comment by alexflav23** [comment]
Hi @EddyP23,

We didn't realise that would be a problem, but that's something we control and that's invisible to the user so we can certainly rename that operator. Thank you for the bug report, it will be fixed as part of the next release.

Regards,
Flavian

**Comment by alexflav23** [comment]
Hi @EddyP23 This is being fixed in the next release, it will be on Maven Central shortly.
