### ISSUE TITLE
Missing cassandra-driver-core dependency for phantom-sbt

### ISSUE THREAD

**Issue by hsn10** [outworkers/phantom#746]
phantom-sbt depends on cassandra unit, but _cassandraunit_ have _cassandra-driver-core_ listed as **optional** dependency so its not pulled automatically into phantom-sbt module. This leads to _ClassNotFoundException_ exception:

```
Caused by: java.lang.ClassNotFoundException: com.datastax.driver.core.QueryOptions
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:139)
```

until **phantom-sbt** plugin is updated, workaround it to add dependency to yours _plugins.sbt_ file:

```
// latest Cassandra driver
libraryDependencies += "com.datastax.cassandra" % "cassandra-driver-core" % "3.3.0"

```

**Comment by alexflav23** [comment]
Hi @hsn10,

Fixed for the next release, thank you for reporting the problem.

Regards,
