### ISSUE TITLE
Boxed error ?

### ISSUE THREAD

**Issue by kczulko** [outworkers/phantom#812]
This is my stack trace from application startup.
```
[info] 2018-02-19 12:21:34.747 [ForkJoinPool-3-worker-15] ERROR c.q.s.r.ServiceRunner$$anonfun$runService$7 - Failed to start
[info] java.util.concurrent.ExecutionException: Boxed Error
[info] 	at scala.concurrent.impl.Promise$.resolver(Promise.scala:59)
[info] 	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:51)
[info] 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
[info] 	at scala.concurrent.Promise$class.complete(Promise.scala:55)
[info] 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:157)
[info] 	at scala.concurrent.Promise$class.failure(Promise.scala:104)
[info] 	at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:157)
[info] 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:257)
[info] 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
[info] 	at scala.concurrent.impl.CallbackRunnable.run_aroundBody0(Promise.scala:36)
[info] 	at scala.concurrent.impl.CallbackRunnable$AjcClosure1.run(Promise.scala:1)
[info] 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
[info] 	at kamon.scala.instrumentation.FutureInstrumentation$$anonfun$aroundExecution$1.apply(FutureInstrumentation.scala:45)
[info] 	at kamon.trace.Tracer$.withContext(TracerModule.scala:58)
[info] 	at kamon.scala.instrumentation.FutureInstrumentation.aroundExecution(FutureInstrumentation.scala:44)
[info] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:35)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] 	at java.lang.Thread.run(Thread.java:748)
[info] Caused by: java.lang.AssertionError: assertion failed
[info] 	at scala.Predef$.assert(Predef.scala:156)
[info] 	at scala.reflect.runtime.JavaMirrors$JavaMirror.scalaSimpleName(JavaMirrors.scala:966)
[info] 	at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$classToScala1(JavaMirrors.scala:988)
[info] 	at scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:980)
[info] 	at scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:980)
[info] 	at scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$toScala$1.apply(JavaMirrors.scala:97)
[info] 	at scala.reflect.runtime.TwoWayCaches$TwoWayCache$$anonfun$toScala$1.apply(TwoWayCaches.scala:38)
[info] 	at scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[info] 	at scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[info] 	at scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:33)
[info] 	at scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:95)
[info] 	at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:980)
[info] 	at scala.reflect.runtime.JavaMirrors$JavaMirror.classSymbol(JavaMirrors.scala:196)
[info] 	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaInstanceMirror.symbol(JavaMirrors.scala:234)
[info] 	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaInstanceMirror.symbol(JavaMirrors.scala:233)
[info] 	at com.outworkers.phantom.column.AbstractColumn$class.com$outworkers$phantom$column$AbstractColumn$$_name(AbstractColumn.scala:55)
[info] 	at com.outworkers.phantom.column.OptionalColumn.com$outworkers$phantom$column$AbstractColumn$$_name$lzycompute(OptionalColumn.scala:22)
[info] 	at com.outworkers.phantom.column.OptionalColumn.com$outworkers$phantom$column$AbstractColumn$$_name(OptionalColumn.scala:22)
[info] 	at com.outworkers.phantom.column.AbstractColumn$class.name(AbstractColumn.scala:58)
[info] 	at com.outworkers.phantom.column.OptionalColumn.name(OptionalColumn.scala:22)
[info] 	at com.outworkers.phantom.column.OptionalPrimitiveColumn.qb(OptionalPrimitiveColumn.scala:39)
[info] 	at com.outworkers.phantom.builder.query.RootCreateQuery$$anonfun$lightweight$1.apply(CreateQuery.scala:49)
[info] 	at com.outworkers.phantom.builder.query.RootCreateQuery$$anonfun$lightweight$1.apply(CreateQuery.scala:49)
[info] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info] 	at scala.collection.immutable.List.foreach(List.scala:392)
[info] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[info] 	at scala.collection.immutable.List.map(List.scala:296)
[info] 	at com.outworkers.phantom.builder.query.RootCreateQuery.lightweight(CreateQuery.scala:49)
[info] 	at com.outworkers.phantom.builder.query.RootCreateQuery.ifNotExists(CreateQuery.scala:72)
[info] 	at myapp.database.RuntimeDatabase$$$$ca9ec021dc1b8858d6ea5e2d0176690$$$$nonfun$apply$13.apply(RuntimeDatabase.scala:74)
[info] 	at myapp.database.RuntimeDatabase$$$$ca9ec021dc1b8858d6ea5e2d0176690$$$$nonfun$apply$13.apply(RuntimeDatabase.scala:73)
[info] 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
[info] 	... 11 common frames omitted

```
phantomDsl = `2.20.0`
scalaVersion = `2.11.12`
```
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

I observe such behavior (Boxed Error) only for ubuntu. Works fine on macOs High Sierra v. 10.13.3 and

```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by alexflav23** [comment]
Hi @kczulko I think this is something to do with how Kamon does instrumentation. We are happy to look further into this, but can you put together a small repo replicating the issue inside a test?

**Comment by alexflav23** [comment]
As we never heard back about this, I will close the ticket. If you do re-open, please provide more information so we can accurately debug.
