### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/reflect/runtime/package$ with v2.30.0

### ISSUE THREAD

**Issue by vichu** [outworkers/phantom#872]
I am using an sbt project with the following dependencies.

```
libraryDependencies ++= Seq(

  //"de.heikoseeberger" %% "akka-http-circe" % "1.22.0",

  // Database dependencies
  "com.outworkers" % "phantom-dsl_2.12" % "2.30.0",

  // scala logging
  "org.slf4j" % "slf4j-api" % "1.7.25",
  "org.slf4j" % "slf4j-simple" % "1.7.25"
)
```
If everything works well if I uncomment the dependency 
`"de.heikoseeberger" %% "akka-http-circe" % "1.22.0"`
When I comment this dependency, I get the following runtime exception.

```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/runtime/package$
	at com.outworkers.phantom.column.AbstractColumn.com$outworkers$phantom$column$AbstractColumn$$_name(AbstractColumn.scala:55)
	at com.outworkers.phantom.column.AbstractColumn.com$outworkers$phantom$column$AbstractColumn$$_name$(AbstractColumn.scala:54)
	at com.outworkers.phantom.column.Column.com$outworkers$phantom$column$AbstractColumn$$_name$lzycompute(Column.scala:22)
	at com.outworkers.phantom.column.Column.com$outworkers$phantom$column$AbstractColumn$$_name(Column.scala:22)
	at com.outworkers.phantom.column.AbstractColumn.name(AbstractColumn.scala:58)
	at com.outworkers.phantom.column.AbstractColumn.name$(AbstractColumn.scala:58)
	at com.outworkers.phantom.column.Column.name(Column.scala:22)
	at com.outworkers.phantom.builder.query.InsertQuery.value(InsertQuery.scala:107)
	at com.indywiz.springorama.phantom.example.database.model.UserById.createUserById(User.scala:44)
	at com.indywiz.springorama.phantom.example.database.service.UserDatabaseService.createUser(UserDatabaseService.scala:15)
	at com.indywiz.springorama.phantom.example.database.service.UserDatabaseService.createUser$(UserDatabaseService.scala:14)
	at com.indywiz.springorama.phantom.example.Main$databaseService$.createUser(Main.scala:24)
	at com.indywiz.springorama.phantom.example.Main$.delayedEndpoint$com$indywiz$springorama$phantom$example$Main$1(Main.scala:32)
	at com.indywiz.springorama.phantom.example.Main$delayedInit$body.apply(Main.scala:11)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.indywiz.springorama.phantom.example.Main$.main(Main.scala:11)
	at com.indywiz.springorama.phantom.example.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.reflect.runtime.package$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
```

I'm getting the exception from the method call `createUserById`, So , I'm also including this peice of the code. 
```
def createUserById(uuid: UUID, firstName: String, lastName: String, emailId: String): Future[ResultSet] = {
  insert
    .value(_.id, uuid)
    .value(_.fName, firstName)
    .value(_.lName, lastName)
    .value(_.email, emailId)
    .future()
}
```
Not sure what id going wrong here. I am using `Scala v2.12.7`. Happy to help with more information if needed. I guess there is some sort of compatability issue here.

Thanks

**Comment by alexflav23** [comment]
Hi @vichu,

Try adding `"org.scala-lang" % "scala-reflect" % scalaVersion.value` as a dependency as well and see if that fixes the problem. It's not a long term solution, but at least it helps us pinpoint the issue to a specific thing.

Let me know once you've had a chance to do that.

Regards.

**Comment by alexflav23** [comment]
HI @vichu Did the above suggestion work? Please re-open this issue if it didn't.
