### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/Serializable

### ISSUE THREAD

**Issue by SarpongAbasimi** [outworkers/phantom#931]
Hey I keep seeing this error 

```
import java.util.UUID

case class Song(
                 id: UUID,
                 title: String,
                 album: String,
                 artist: String
               )
```

```
import com.outworkers.phantom.dsl._

scala> abstract class SongsModel extends Table[SongsModel, Song] {
     | 
     |   override def tableName: String = "songs"
     | 
     |   object id extends TimeUUIDColumn with PartitionKey {
     |     override lazy val name = "song_id"
     |   }
     | 
     |   object artist extends StringColumn
     |   object title extends StringColumn
     |   object album extends StringColumn
     | 
     |   def getBySongId(id: UUID): Future[Option[Song]] = {
     |     select
     |       .where(_.id eqs id)
     |       .consistencyLevel_=(ConsistencyLevel.ONE)
     |       .one()
     |   }
     | 
     |   def deleteById(id: UUID): Future[ResultSet] = {
     |     delete
     |       .where(_.id eqs id)
     |       .consistencyLevel_=(ConsistencyLevel.ONE)
     |       .future()
     |   }
     | }

```

# Error message

```
java.lang.NoClassDefFoundError: scala/Serializable
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetPublicMethods(Class.java:2902)
        at java.lang.Class.getMethods(Class.java:1615)
        at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.resolveJavaReflectionRuntime(JavaReflectionRuntimes.scala:29)
        at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.resolveJavaReflectionRuntime$(JavaReflectionRuntimes.scala:27)
        at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveJavaReflectionRuntime(MacroRuntimes.scala:61)
        at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveRuntime(MacroRuntimes.scala:74)
        at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$standardMacroRuntime$3(MacroRuntimes.scala:47)
        at scala.collection.mutable.MapOps.getOrElseUpdate(Map.scala:146)
        at scala.collection.mutable.MapOps.getOrElseUpdate$(Map.scala:143)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:265)
        at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime(MacroRuntimes.scala:47)
        at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime$(MacroRuntimes.scala:40)
        at scala.tools.nsc.Global$$anon$6.standardMacroRuntime(Global.scala:485)
        at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$13.default(AnalyzerPlugins.scala:489)
        at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$13.default(AnalyzerPlugins.scala:486)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:427)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime(AnalyzerPlugins.scala:486)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime$(AnalyzerPlugins.scala:486)
        at scala.tools.nsc.Global$$anon$6.pluginsMacroRuntime(Global.scala:485)
        at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime(MacroRuntimes.scala:34)
        at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime$(MacroRuntimes.scala:34)
        at scala.tools.nsc.Global$$anon$6.macroRuntime(Global.scala:485)
        at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:575)
        at scala.tools.nsc.Global.withInfoLevel(Global.scala:228)
        at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:569)
        at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:556)
        at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:731)
        at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:729)
        at scala.tools.nsc.Global$$anon$6.standardMacroExpand(Global.scala:485)
        at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$11.default(AnalyzerPlugins.scala:473)
        at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$11.default(AnalyzerPlugins.scala:470)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:427)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:470)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:470)
        at scala.tools.nsc.Global$$anon$6.pluginsMacroExpand(Global.scala:485)
        at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:720)
        at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:713)
        at scala.tools.nsc.Global$$anon$6.macroExpand(Global.scala:485)
        at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1209)
        at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1278)
        at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1251)
        at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1271)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:873)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit0(Implicits.scala:810)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$typedImplicit(Implicits.scala:629)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1208)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:1245)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1302)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1722)
        at scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:113)
        at scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
        at scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:89)
        at scala.tools.nsc.Global$$anon$6.inferImplicit(Global.scala:485)
        at scala.tools.nsc.typechecker.Implicits.inferImplicitFor(Implicits.scala:47)
        at scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:46)
        at scala.tools.nsc.Global$$anon$6.inferImplicitFor(Global.scala:485)
        at scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:263)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:869)
        at scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:497)
        at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1274)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6056)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6119)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3410)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3410)
        at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2564)
        at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5960)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5995)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6041)
        at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:6117)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5950)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6041)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6119)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3410)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3410)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2064)
        at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1895)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5951)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6041)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6119)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3410)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3410)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2064)
        at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1895)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5951)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6041)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6119)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3410)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3410)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2064)
        at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1895)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5951)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6041)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6119)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3410)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3410)
        at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5634)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5954)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6041)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:112)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:101)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1519)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1503)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:744)
        at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:960)
        at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:533)
        at scala.tools.nsc.interpreter.IMain.doInterpret(IMain.scala:519)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:503)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:501)
        at scala.tools.nsc.interpreter.shell.ILoop.loop$1(ILoop.scala:878)
        at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:906)
        at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:433)
        at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:440)
        at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:458)
        at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:968)
        at xsbt.ConsoleBridge.run(ConsoleBridge.scala:78)
        at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:208)
        at sbt.Console.console0$1(Console.scala:64)
        at sbt.Console.$anonfun$apply$5(Console.scala:74)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
        at sbt.TrapExit$App.run(TrapExit.scala:258)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala.Serializable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 136 more

```

Any input as this why this may be? I know it has to do with `java.lang.ClassNotFoundException: scala.Serializable`
but I am not sure where that is coming from. And I don't think I am missing any imports based on this

Ref - https://github.com/outworkers/phantom/blob/develop/docs_bkp/basics/database.md

**Comment by SarpongAbasimi** [comment]
Also using 
```
scalaVersion := "2.13.6"
lazy val phantomVersion = "2.59.0"

libraryDependencies += "com.outworkers" % "phantom-dsl_2.11" % phantomVersion
```

**Comment by arixmkii** [comment]
```scala
libraryDependencies += "com.outworkers" % "phantom-dsl_2.11" % phantomVersion
```

@SarpongAbasimi do you really want phantom dsl built for Scala 2.11, when you are building for Scala 2.13.6?

If it is a snippet from SBT, then you probably want

```scala
scalaVersion := "2.13.6"
lazy val phantomVersion = "2.59.0"

libraryDependencies += "com.outworkers" %% "phantom-dsl" % phantomVersion
```

**Comment by SarpongAbasimi** [comment]
sure, thank you very much 😊
